### ISSUE TITLE
table requirements: which column needs to be called ASV? should it be ASV/OTU or something generic?

### ISSUE THREAD

**Issue by jsevo** [jsevo/taxumap#14]

**Comment by funnell** [comment]
Hi @jsevo, my vote would be something more generic, or be able to specify the name of the most specific column. For context, I've been using TaxUMAP on shotgun data.

**Comment by jsevo** [comment]
That's a great suggestion. Grant take note. We should do that and set a
generic name to default. This should be the column name used in all
examples so a user could format the tables without having to provide a
keyword argument.

**Comment by granthussey** [comment]
As for table column requirements, the only one should be the _indices_ of the `microbiome_data` and `taxonomy` tables. The index of the `taxonomy` table should be `'ASV'` or `'OTU'`. The index of the `microbiome_data` should be `'index_column'`.

Let me confirm this.

I wonder if 2.0 version of this project be called "hierarchical UMAP" (or hUMAP or something).
