### ISSUE TITLE
Explanation for flags in README

### ISSUE THREAD

**Issue by anadj-micro** [jsevo/taxumap#8]
It would be good to have a more extensive explanation on how to use flags '-a' or '-w'. For example, how to use '-a' if there is only one taxonomic level you want to group at (and if this is possible). Similarly '-w' flag explanation doesn't state what are the limits for weights (0-10?); and if bigger numbers mean more weight to that taxonomic level. An example would be great.

**Comment by granthussey** [comment]
We will defined create docs that describe these in a lot more detail. For now, the short readme will incorporate some more examples and explanation. Thank you!
